services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: docker4rajashekar/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    build: ./catalogue
    image: docker4rajashekar/catalogue:v1
    container_name: catalogue
  frontend:
    build: ./frontend
    image: docker4rajashekar/frontend:v1
    container_name: frontend
    ports: 
    - 80:80
  redis:
    image: redis:7
    container_name: redis
    volumes:
    - redis:/data
  user:
    build: ./user
    image: docker4rajashekar/user:v1
    container_name: user
  cart:
    build: ./cart
    image: docker4rajashekar/cart:v1
    container_name: cart
  mysql:
    build: ./mysql
    image: docker4rajashekar/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    build: ./shipping
    image: docker4rajashekar/shipping:v1
    container_name: shipping
  payment:
    build: ./payment
    image: docker4rajashekar/payment:v1
    container_name: payment
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123

networks:
  default: 
    driver: bridge
    name: roboshop
    external: false
volumes:
  mysql:
  rabbitmq:
  mongodb:
  redis: